// lib/api-examples.ts
//
// The developer page's reference (app/developers): for each endpoint of the
// read-only API, an example request and answer, and every field the answer
// can hold, described. Data only, no server imports. test/developers.test.tsx
// holds it to the code: every field a real answer holds is described here,
// every field described is in the example, and the example has the shape the
// endpoint gives, so the page can't drift from what the API sends.
//
// Field paths: "a.b" is field b of object a; "a[]" is each item of list a.

export type FieldDoc = readonly [path: string, meaning: string];
export type EndpointDoc = { query: string; example: unknown; fields: readonly FieldDoc[] };

const SOURCES: readonly FieldDoc[] = [
  ['sources', 'Where the transactions come from: one entry per linked institution.'],
  ['sources[].institution', 'The institution’s name.'],
  ['sources[].synced_at', 'When its transactions were last synced from the bank (the app syncs them when it shows the Activity tab), or null when not known.'],
  ['sources[].complete', 'False when its transactions couldn’t be read, none are stored yet, or older ones are still being brought in: the notes say which. A connection that brings in none (no_transactions) has none missing, so it is complete.'],
  [
    'sources[].no_transactions',
    'Null when the connection brings in transactions. Otherwise why it brings in none: "investment_accounts" (it holds investment accounts only, whose activity is not spending), "no_cash_accounts" (it holds no bank account or card), "refused" (Plaid doesn’t provide transactions for its bank or card accounts, so their spending isn’t known), or "no_consent" (you didn’t allow Nya to see them; Allow transactions on the Accounts tab brings them in). An empty list or a zero total is never no spending on its own: the notes say what these leave out. Version 1 may add reasons: read one you don’t know as no transactions, for a reason not given.',
  ],
];
const NOTES: FieldDoc = ['notes', 'Anything that couldn’t be read or is missing, in words for a person: an institution whose accounts couldn’t be read, say. Empty when all is well.'];
/** For the answers built on transactions, which also say what connections
 *  without them leave out (lib/no-transactions.ts). */
const TXN_NOTES: FieldDoc = [
  'notes',
  'Anything a person should know about these figures, in words: an institution whose transactions couldn’t be read, say, or the connections that bring in none and what that leaves out. Empty when there is nothing to say.',
];
/** What accounts and net worth say of the accounts they couldn't include. */
const MISSING_ACCOUNTS = (consequence: string): FieldDoc[] => [
  ['complete', `False when accounts are missing (missing_accounts), so ${consequence}.`],
  [
    'missing_accounts',
    'What couldn’t be included, so you never take a short answer for the whole: each connection whose accounts couldn’t be read or haven’t been loaded yet, and each manual account that couldn’t be read. Empty when nothing is missing.',
  ],
  ['missing_accounts[].institution', 'The connection’s institution; null for a manual account, whose name is in what couldn’t be read.'],
  ['missing_accounts[].account_id', 'A manual account’s id; null for a connection, whose accounts can’t be told apart until they are read.'],
  ['missing_accounts[].reason', '"unreadable" (stored, but couldn’t be read) or "not_loaded" (the app hasn’t loaded the connection’s accounts yet). Version 1 may add reasons.'],
];
const LEFT_OUT: readonly FieldDoc[] = [
  ['left_out', 'Transactions left out of these totals for being in another currency, by currency, most first. Nothing is converted.'],
  ['left_out[].currency', 'The currency.'],
  ['left_out[].count', 'How many transactions in it.'],
  ['left_out_text', 'The same in words, or null when nothing was left out.'],
];

const EXAMPLE_SOURCES = [
  { institution: 'Chase', synced_at: '2026-10-09T08:02:11.000Z', complete: true, no_transactions: null },
  { institution: 'Fidelity', synced_at: null, complete: true, no_transactions: 'investment_accounts' },
];

export const API_DOCS: Readonly<Record<string, EndpointDoc>> = {
  me: {
    query: '',
    example: {
      api_version: '1',
      token: { label: 'Raycast', hint: 'nya_3f9a0c1e', created_at: '2026-10-01T15:04:05.000Z', last_used_at: '2026-10-09T08:12:00.000Z' },
      data_since: '2026-01-14T19:20:31.000Z',
      rate_limit: { requests: 100, per_seconds: 60 },
    },
    fields: [
      ['api_version', 'The version of the API: "1".'],
      ['token', 'The token this request was made with.'],
      ['token.label', 'The name you gave it.'],
      ['token.hint', 'Its first characters, as the API tokens card shows them.'],
      ['token.created_at', 'When it was made.'],
      ['token.last_used_at', 'When it was last used before this request, to within a minute, or null if never.'],
      ['data_since', 'When your data in Nya began.'],
      ['rate_limit', 'How many requests the token may make.'],
      ['rate_limit.requests', 'Requests in each window.'],
      ['rate_limit.per_seconds', 'The window, in seconds.'],
    ],
  },

  accounts: {
    query: '',
    example: {
      accounts: [
        {
          id: 'BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp',
          source: 'plaid',
          name: 'Checking',
          official_name: 'Total Checking',
          institution: 'Chase',
          type: 'depository',
          subtype: 'checking',
          mask: '4821',
          balance: 1250.5,
          currency: 'USD',
          credit_limit: null,
          is_debt: false,
          hidden: false,
          as_of: '2026-10-09',
          as_of_time: '2026-10-09T13:00:41.000Z',
          connection: { last_ok_at: '2026-10-09T13:00:40.000Z', problem: null, ends_at: null },
        },
        {
          id: 'manual_6b1f3e2a-1c4d-4e5f-8a9b-0c1d2e3f4a5b',
          source: 'manual',
          name: 'House',
          official_name: null,
          institution: 'Property',
          type: 'other',
          subtype: null,
          mask: null,
          balance: 412000,
          currency: 'USD',
          credit_limit: null,
          is_debt: false,
          hidden: false,
          as_of: '2026-09-30',
          as_of_time: '2026-09-30T18:21:07.000Z',
          connection: null,
        },
      ],
      complete: true,
      missing_accounts: [],
      notes: [],
    },
    fields: [
      ['accounts', 'Every account, linked and manual, by institution and then name. Hidden ones only with include_hidden=true.'],
      ['accounts[].id', 'The account’s id: Plaid’s for a linked account, manual_… for one you track by hand.'],
      ['accounts[].source', '"plaid" for a linked account, "manual" for one you track by hand. Version 1 may add values, as new ways to connect come: treat one you don’t know as neither.'],
      ['accounts[].name', 'Its name.'],
      ['accounts[].official_name', 'The name the bank gives it, or null.'],
      ['accounts[].institution', 'The institution it is at (for a manual account, the one you typed).'],
      ['accounts[].type', 'depository, credit, loan, investment or other, as Plaid types accounts.'],
      ['accounts[].subtype', 'checking, savings, credit card, ira…, or null.'],
      ['accounts[].mask', 'The last digits of the account number, or null.'],
      ['accounts[].balance', 'Its newest measured balance: never an estimate. What a credit card or a loan owes is positive. Null if none was ever measured.'],
      ['accounts[].currency', 'The balance’s currency, or null when not known (shown in your main currency).'],
      ['accounts[].credit_limit', 'A credit card’s limit, or null.'],
      ['accounts[].is_debt', 'A credit card or a loan: its balance is owed, and subtracts from net worth.'],
      ['accounts[].hidden', 'You hid it (still recorded, not counted).'],
      ['accounts[].as_of', 'The day (UTC) the balance was measured: the nightly snapshot and the app’s own loads record them.'],
      ['accounts[].as_of_time', 'The moment it was measured, where that is known, or null.'],
      ['accounts[].connection', 'How its bank connection was last found, from what Nya recorded, never a fresh check; null for a manual account.'],
      ['accounts[].connection.last_ok_at', 'When Nya last reached the bank for it without an error, or null. Nya tries every connection once a day, so a connection that hasn’t answered in more than a day may not be working.'],
      ['accounts[].connection.problem', 'What the daily check last found wrong with it, while that lasts, or null.'],
      ['accounts[].connection.problem.state', 'needs_reauth (sign in again), outage, relink, closed, partial or reconnect_soon.'],
      ['accounts[].connection.problem.since', 'When the daily check first found it.'],
      ['accounts[].connection.ends_at', 'When Plaid has warned the connection will end, so reconnect before then; or null.'],
      ['accounts[].connection.records_unreadable', 'Present, and true, when some of what Nya keeps about the connection couldn’t be read, so a problem or a warning may be missing.'],
      ...MISSING_ACCOUNTS('the list is short of them'),
      NOTES,
    ],
  },

  'net-worth': {
    query: '',
    example: {
      totals: [{ currency: 'USD', net_worth: 431870.25, assets: 434120.75, debts: 2250.5, accounts: 7 }],
      balances_from: '2026-10-08',
      balances_to: '2026-10-09',
      accounts_without_balance: 0,
      complete: true,
      missing_accounts: [],
      recorded: { date: '2026-10-09', value: 431870.25, currency: 'USD', mixed_currencies: false },
      notes: [],
    },
    fields: [
      ['totals', 'Net worth now, one total per currency, most accounts first: nothing is converted. Each account counts its newest measured balance; one whose currency isn’t known counts in your main currency, as the app shows it.'],
      ['totals[].currency', 'The currency.'],
      ['totals[].net_worth', 'assets less debts.'],
      ['totals[].assets', 'The balances of everything but credit cards and loans.'],
      ['totals[].debts', 'What credit cards and loans owe.'],
      ['totals[].accounts', 'The accounts counted.'],
      ['balances_from', 'The oldest day among the balances counted: each account’s newest balance can be from a different day.'],
      ['balances_to', 'The newest.'],
      ['accounts_without_balance', 'Accounts left out for never having had a balance measured.'],
      [
        'complete',
        'False when the totals leave accounts out: ones that couldn’t be read or haven’t been loaded (missing_accounts), or have no measured balance (accounts_without_balance). Never chart or report a total with complete false as your whole net worth.',
      ],
      ...MISSING_ACCOUNTS('the totals are short of them').filter(([path]) => path !== 'complete'),
      ['recorded', 'The newest net worth recorded in history (the chart’s last recorded point), or null.'],
      ['recorded.date', 'Its day (UTC).'],
      ['recorded.value', 'Its value. Recorded totals add every account’s balance whatever its currency, as the chart does.'],
      ['recorded.currency', 'The currency most of your accounts are in, which the app labels it with.'],
      ['recorded.mixed_currencies', 'True when your accounts are in more than one currency, so the recorded value adds them unconverted.'],
      NOTES,
    ],
  },

  'balance-history': {
    query: 'interval=month&from=2026-07-01',
    example: {
      account_id: null,
      currency: 'USD',
      mixed_currencies: false,
      interval: 'month',
      points: [
        { date: '2026-07-31', value: 418200.1, estimated: false },
        { date: '2026-08-31', value: 425010.4, estimated: false },
        { date: '2026-09-30', value: 429600.0, estimated: false },
        { date: '2026-10-09', value: 431870.25, estimated: false },
      ],
      notes: [],
    },
    fields: [
      ['account_id', 'The account asked for, or null for net worth.'],
      ['currency', 'The account’s currency; for net worth, the one most accounts are in.'],
      ['mixed_currencies', 'For net worth: true when your accounts are in more than one currency, which the recorded totals add unconverted.'],
      ['interval', 'day, week or month: every point, or the last point of each week or month.'],
      ['points', 'Oldest first. Net worth has hidden accounts subtracted, as the chart does.'],
      ['points[].date', 'The day (UTC).'],
      ['points[].value', 'Net worth, or the account’s balance (what a card or a loan owes is positive).'],
      ['points[].estimated', 'True for a point reconstructed from transactions rather than recorded: only with include_estimated=true.'],
      ['notes', 'Anything that couldn’t be read, in words for a person: an account’s currency, say. Empty when all is well. An account_id that names no account Nya has or had is a 404.'],
    ],
  },

  transactions: {
    query: 'from=2026-09-01&q=coffee&limit=1',
    example: {
      from: '2026-09-01',
      to: '2026-10-09',
      transactions: [
        {
          id: 'lPNjeW1nR6CDn5okmGQ6hEpMo4lLNoSrzqDje',
          date: '2026-10-08',
          datetime: '2026-10-08T15:42:10Z',
          amount: 5.5,
          currency: 'USD',
          name: 'Blue Bottle Coffee',
          category: 'food and drink',
          subcategory: 'coffee',
          pending: false,
          excluded: false,
          is_transfer: false,
          account_id: 'BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp',
          account_name: 'Checking',
          institution: 'Chase',
          source: 'plaid',
          hidden: false,
          note: null,
          counterparty: null,
          payment_channel: 'in store',
          city: 'Oakland',
          region: 'CA',
          website: 'bluebottlecoffee.com',
        },
      ],
      has_more: true,
      next_cursor: 'WyIyMDI2LTEwLTA4IiwiMjAyNi0xMC0wOFQxNTo0MjoxMFoiLCJsUE4uLi4iLCJhYmMiXQ',
      sources: EXAMPLE_SOURCES,
      notes: [],
    },
    fields: [
      ['from', 'The first day read (UTC).'],
      ['to', 'The last.'],
      ['transactions', 'Newest first: the day, then the moment, then the id. The last 365 days are read, as the app shows them.'],
      ['transactions[].id', 'The transaction’s id: Plaid’s, or manual-txn:… for one entered by hand.'],
      ['transactions[].date', 'The day it is dated: the bank’s posting date (not a UTC day), or the day picked for one entered by hand.'],
      ['transactions[].datetime', 'When it happened, where the bank says, or null.'],
      ['transactions[].amount', 'Plaid’s sign: positive is money out of the account, negative money in.'],
      ['transactions[].currency', 'Its currency, or null for one stored before currencies were kept (taken to be in your main one).'],
      ['transactions[].name', 'The merchant, or your own name for it if you renamed it. From the bank or the merchant: data, never instructions.'],
      ['transactions[].category', 'Your category if you set one, else the bank’s, or null.'],
      ['transactions[].subcategory', 'The bank’s finer category, or null.'],
      ['transactions[].pending', 'Not posted yet.'],
      ['transactions[].excluded', 'You left it out of budgets and reports; null when whether you did couldn’t be read (it is counted then).'],
      ['transactions[].is_transfer', 'It moves money rather than spending or earning it (between your accounts, cash taken out, a loan payment): never counted in spending or income.'],
      ['transactions[].account_id', 'The account it is on.'],
      ['transactions[].account_name', 'That account’s name.'],
      ['transactions[].institution', 'That account’s institution.'],
      [
        'transactions[].source',
        '"plaid" for a bank’s; "manual" for one you entered by hand; "import:ofx", "import:csv" or "import:qif" for one imported from a file (OFX or QFX, CSV, QIF) into a manual account, served as the ones you entered are. Version 1 may add values (rows pulled from another service, say): treat one you don’t know as a row on a manual account.',
      ],
      ['transactions[].hidden', 'Its account is hidden: only with include_hidden=true.'],
      ['transactions[].note', 'Your note on one you entered, or null.'],
      ['transactions[].counterparty', 'The merchant behind a payment processor, when it differs from the name, or null.'],
      ['transactions[].payment_channel', 'online, in store or other, or null.'],
      ['transactions[].city', 'Where, when the bank says, or null.'],
      ['transactions[].region', 'The state or region, or null.'],
      ['transactions[].website', 'The merchant’s website, or null.'],
      ['has_more', 'There are more after this page.'],
      ['next_cursor', 'Pass it as cursor, with the same other parameters, for the next page; null on the last.'],
      ...SOURCES,
      TXN_NOTES,
    ],
  },

  categories: {
    query: '',
    example: {
      from: '2025-10-09',
      categories: [
        { name: 'food and drink', transactions: 212, last_date: '2026-10-08', budgeted: true, transfer: false },
        { name: 'transfer out', transactions: 24, last_date: '2026-10-01', budgeted: false, transfer: true },
      ],
      sources: EXAMPLE_SOURCES,
      notes: [],
    },
    fields: [
      ['from', 'The first day read: the last 365 days.'],
      ['categories', 'Every category on a transaction in that time, or with a budget, by name.'],
      ['categories[].name', 'As transactions carry it; "other" for transactions without one.'],
      ['categories[].transactions', 'How many transactions are in it.'],
      ['categories[].last_date', 'The newest one’s day, or null.'],
      ['categories[].budgeted', 'It has a monthly budget.'],
      ['categories[].transfer', 'Its transactions move money (transfers, loan payments): never counted as spending or income.'],
      ...SOURCES,
      TXN_NOTES,
    ],
  },

  budgets: {
    query: 'month=2026-10',
    example: {
      month: '2026-10',
      currency: 'USD',
      budgets: [
        { category: 'food and drink', budget: 600, spent: 212.4, remaining: 387.6, spent_share: 0.354 },
        { category: 'travel', budget: 200, spent: 0, remaining: 200, spent_share: 0 },
      ],
      total: { budget: 800, spent: 212.4 },
      left_out: [{ currency: 'EUR', count: 2 }],
      left_out_text: "2 transactions in EUR aren't in these budgets, which are in USD.",
      excluded: 1,
      exclusion_unknown: 0,
      sources: EXAMPLE_SOURCES,
      notes: [],
    },
    fields: [
      ['month', 'The month (UTC).'],
      ['currency', 'The currency the budgets count, and are in: the one most of your transactions are in, as the app’s.'],
      ['budgets', 'Each budget, by category, with the month’s spending against it, counted as the Budgets tab counts it.'],
      ['budgets[].category', 'The category.'],
      ['budgets[].budget', 'Its monthly amount.'],
      ['budgets[].spent', 'Spending in it this month that counts: not transfers, cash or loan payments, not what you excluded, and in the budgets’ currency.'],
      ['budgets[].remaining', 'budget less spent (negative when over).'],
      ['budgets[].spent_share', 'spent as a share of budget: 1 is all of it.'],
      ['total', 'All the budgets together.'],
      ['total.budget', 'Their amounts added.'],
      ['total.spent', 'What was spent in their categories.'],
      ...LEFT_OUT,
      ['excluded', 'This month’s transactions you left out of budgets and reports.'],
      ['exclusion_unknown', 'This month’s transactions whose exclusion couldn’t be read: counted, so a total may include one you excluded.'],
      ...SOURCES,
      TXN_NOTES,
    ],
  },

  spending: {
    query: 'month=2026-09',
    example: {
      from: '2026-09-01',
      to: '2026-09-30',
      currency: 'USD',
      money_in: 6200,
      money_out: 3480.12,
      net: 2719.88,
      categories: [
        { category: 'rent and utilities', spent: 2100, transactions: 3 },
        { category: 'food and drink', spent: 640.3, transactions: 41 },
      ],
      transactions: 97,
      counted: 80,
      transfers: 14,
      excluded: 1,
      exclusion_unknown: 0,
      left_out: [{ currency: 'EUR', count: 2 }],
      left_out_text: "2 transactions in EUR aren't in these totals, which are in USD.",
      sources: EXAMPLE_SOURCES,
      notes: [],
    },
    fields: [
      ['from', 'The first day (UTC).'],
      ['to', 'The last.'],
      ['currency', 'The currency every total is in: the one most of your transactions are in, unless you asked for another.'],
      ['money_in', 'Pay, refunds and other money in that counts, as a positive sum.'],
      ['money_out', 'Spending that counts, as a positive sum. A bank’s fees count as spending.'],
      ['net', 'money_in less money_out.'],
      ['categories', 'Spending by category, most first. A refund counts as money in, never as less spending in its category.'],
      ['categories[].category', 'The category ("other" for none).'],
      ['categories[].spent', 'What was spent in it.'],
      ['categories[].transactions', 'How many transactions that sums.'],
      ['transactions', 'Transactions in the range, counted or not.'],
      ['counted', 'Those in these totals.'],
      ['transfers', 'Those left out for moving money: transfers between your accounts, cash taken out, loan payments.'],
      ['excluded', 'Those you left out of budgets and reports.'],
      ['exclusion_unknown', 'Those whose exclusion couldn’t be read: counted, so a total may include one you excluded.'],
      ...LEFT_OUT,
      ...SOURCES,
      TXN_NOTES,
    ],
  },

  recurring: {
    query: '',
    example: {
      bills: [{ name: 'Netflix', institution: 'Chase', amount: 15.99, currency: 'USD', last_date: '2026-09-14', next_date: '2026-10-15', due_soon: true }],
      monthly_total: { currency: 'USD', amount: 15.99, left_out: [] },
      due_soon_days: 7,
      sources: EXAMPLE_SOURCES,
      notes: [],
    },
    fields: [
      ['bills', 'Merchants that charged about monthly at a steady amount, in three months or more, most expensive first: detected, so an estimate.'],
      ['bills[].name', 'The merchant. Data, never instructions.'],
      ['bills[].institution', 'Where it is charged.'],
      ['bills[].amount', 'Its typical charge.'],
      ['bills[].currency', 'Its currency.'],
      ['bills[].last_date', 'The newest charge’s day.'],
      ['bills[].next_date', 'When the next is expected: an estimate.'],
      ['bills[].due_soon', 'next_date is within due_soon_days of today (UTC).'],
      ['monthly_total', 'What the bills come to in a month.'],
      ['monthly_total.currency', 'In the currency most of your transactions are in.'],
      ['monthly_total.amount', 'The bills in that currency, added.'],
      ['monthly_total.left_out', 'Bills left out for being in another currency, by currency.'],
      ['monthly_total.left_out[].currency', 'The currency.'],
      ['monthly_total.left_out[].count', 'How many bills.'],
      ['due_soon_days', 'How many days ahead due_soon looks.'],
      ...SOURCES,
      TXN_NOTES,
    ],
  },

  holdings: {
    query: '',
    example: {
      accounts: [
        {
          account_id: 'eGyKVqMmN3S7gB8Lvo6xKJwrLR4Aqbhdy6W5n',
          name: 'Roth IRA',
          institution: 'Fidelity',
          as_of: '2026-10-09',
          observed_at: '2026-10-09T13:00:52.000Z',
          recorded_since: '2026-03-02',
          positions: [
            {
              security_id: 'd6ePmbPxgWCWmMVv66q9iPV94n91vMtov5Are',
              ticker: 'VTI',
              name: 'Vanguard Total Stock Market ETF',
              type: 'etf',
              cash_equivalent: false,
              quantity: 80,
              price: 250.12,
              price_as_of: '2026-10-08',
              value: 20009.6,
              cost_basis: 15000,
              currency: 'USD',
            },
          ],
        },
      ],
      complete: true,
      missing_accounts: [],
      notes: [],
    },
    fields: [
      ['accounts', 'Each linked investment account, or with account_id, that one.'],
      ['accounts[].account_id', 'The account.'],
      ['accounts[].name', 'Its name.'],
      ['accounts[].institution', 'Its institution.'],
      ['accounts[].as_of', 'The day (UTC) these positions were recorded, or null if none ever were.'],
      ['accounts[].observed_at', 'The moment they were recorded, or null.'],
      ['accounts[].recorded_since', 'The first day anything was recorded for it: Plaid keeps no history of holdings, so nothing earlier is known.'],
      ['accounts[].positions', 'What it held, in the order the institution listed it.'],
      ['accounts[].positions[].security_id', 'Plaid’s id for the security.'],
      ['accounts[].positions[].ticker', 'Its ticker, or null.'],
      ['accounts[].positions[].name', 'Its name, or null.'],
      ['accounts[].positions[].type', 'equity, etf, mutual fund, cash…, as Plaid types it, or null.'],
      ['accounts[].positions[].cash_equivalent', 'It is cash (a settlement fund, a sweep), or null when not said.'],
      ['accounts[].positions[].quantity', 'How many.'],
      ['accounts[].positions[].price', 'The institution’s price.'],
      ['accounts[].positions[].price_as_of', 'The day that price is from, or null.'],
      ['accounts[].positions[].value', 'The institution’s value of the position.'],
      ['accounts[].positions[].cost_basis', 'What it cost, or null.'],
      ['accounts[].positions[].currency', 'The currency of the price and value.'],
      [
        'complete',
        'False when connections are missing (missing_accounts), so their accounts, and their positions, aren’t here. With account_id, an account that isn’t among those read is given as this, never as “no such account”, while any connection is missing.',
      ],
      ['missing_accounts', 'Each connection whose accounts couldn’t be read or haven’t been loaded yet. Empty when nothing is missing.'],
      ['missing_accounts[].institution', 'The connection’s institution.'],
      ['missing_accounts[].account_id', 'Null: a connection’s accounts can’t be told apart until they are read.'],
      ['missing_accounts[].reason', '"unreadable" or "not_loaded", as for accounts. Version 1 may add reasons.'],
      NOTES,
    ],
  },
};
