// scripts/fire-data.ts
//
// Builds lib/fire/history-data.ts, the monthly US market history the Plan tab
// simulates against, from Robert Shiller's data as packaged by
// github.com/datasets/s-and-p-500. Run it again to reproduce the checked-in
// module byte for byte:
//
//   curl -sSLo /tmp/sp500.csv \
//     https://raw.githubusercontent.com/datasets/s-and-p-500/07b81e6af68239acd65b901a11844d6d95db6ead/data/data.csv
//   bun run fire-data /tmp/sp500.csv
//
// That commit's file has SHA-256 3a45dffa...ecac6 (the full hash is written
// into the module). Later commits only append months, so the rows used here
// are the same in them; the module also records a hash of just those rows,
// which a newer file can be checked against.
//
// Which rows: the leading run of complete months. The package extends the
// index price past the end of Shiller's own series (June 2023) with zeros in
// the dividend, CPI and interest rate columns, and a zero there would read as
// a real number, so the run stops at the first row missing any of them, and
// the script refuses a file where complete rows start again after that.
//
// The derivations themselves (total return from price and dividend, real
// returns, bond returns from the 10-year yield) live in lib/fire/derive.ts,
// where they are tested.
//
// Flags:
//   --out <path>   where to write (default lib/fire/history-data.ts)

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { deriveSeries, isComplete, type DerivedMonth, type ShillerMonth } from '@/lib/fire/derive';

/** Where the checked-in module's input came from. */
export const PINNED_SOURCE = {
  url: 'https://raw.githubusercontent.com/datasets/s-and-p-500/07b81e6af68239acd65b901a11844d6d95db6ead/data/data.csv',
  sha256: '3a45dffabc414afc298c12159abc84c2875f88175ff3d4473ef7417e725ecac6',
};

/** Values are stored as whole millionths: 12345 is a return of +1.2345%. */
export const SCALE = 1_000_000;

const COLUMNS = {
  date: 'Date',
  price: 'SP500',
  dividend: 'Dividend',
  cpi: 'Consumer Price Index',
  longRate: 'Long Interest Rate',
} as const;

export type ParsedCsv = {
  /** Every complete month, in order. */
  rows: ShillerMonth[];
  /** The raw lines of those rows, with the header, for the rows hash. */
  usedLines: string[];
};

/** The leading run of complete months in the packaged CSV. */
export function parseShillerCsv(text: string): ParsedCsv {
  const lines = text.split(/\r?\n/).filter((l) => l.trim() !== '');
  if (lines.length < 3) throw new Error('the file has no data rows');
  const header = lines[0].split(',').map((h) => h.trim());
  const col = (name: string) => {
    const i = header.indexOf(name);
    if (i < 0) throw new Error(`column "${name}" is missing`);
    return i;
  };
  const at = { date: col(COLUMNS.date), price: col(COLUMNS.price), dividend: col(COLUMNS.dividend), cpi: col(COLUMNS.cpi), longRate: col(COLUMNS.longRate) };

  const rows: ShillerMonth[] = [];
  const usedLines = [lines[0]];
  let ended: string | null = null;
  for (const line of lines.slice(1)) {
    const f = line.split(',');
    const date = (f[at.date] ?? '').trim();
    if (!/^\d{4}-\d{2}-01$/.test(date)) throw new Error(`unexpected date "${date}"`);
    const row: ShillerMonth = {
      month: date.slice(0, 7),
      price: Number(f[at.price]),
      dividend: Number(f[at.dividend]),
      cpi: Number(f[at.cpi]),
      longRate: Number(f[at.longRate]),
    };
    if (!isComplete(row)) {
      ended ??= row.month;
      continue;
    }
    if (ended) throw new Error(`complete rows start again at ${row.month} after the data ended at ${ended}`);
    rows.push(row);
    usedLines.push(line);
  }
  return { rows, usedLines };
}

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function series(name: string, doc: string, months: DerivedMonth[], pick: (m: DerivedMonth) => number): string {
  const out = [`/** ${doc} */`, `export const ${name}: readonly number[] = [`];
  for (let i = 0; i < months.length; i += 12) {
    const year = months[i].month.slice(0, 4);
    const values = months.slice(i, i + 12).map((m) => Math.round(pick(m) * SCALE));
    out.push(`  /* ${year} */ ${values.join(', ')},`);
  }
  out.push('];');
  return out.join('\n');
}

/** The module's text, from the CSV's text. */
export function buildModule(csv: string, source: { url: string; sha256: string }): string {
  const { rows, usedLines } = parseShillerCsv(csv);
  const months = deriveSeries(rows);
  const first = months[0].month;
  const last = months[months.length - 1].month;
  const header = `// lib/fire/history-data.ts
//
// GENERATED by scripts/fire-data.ts. Do not edit: change the script and run it
// again (its header says how).
//
// Monthly US market history, one value per month from ${first} to ${last}: the
// return over that month, from its start to the start of the next, in today's
// money, as whole millionths (12345 is +1.2345%). The derivations are in
// lib/fire/derive.ts:
//
//   - STOCKS_REAL: the S&P composite's total return (price change plus a
//     twelfth of the annualized dividend), less inflation.
//   - BONDS_REAL: a 10-year government bond bought at par each month at that
//     month's yield and sold a month later at the next month's yield, plus the
//     month's coupon, less inflation.
//   - INFLATION: the change in the consumer price index.
//
// Source: Robert Shiller's monthly data (Irrational Exuberance; his page is
// http://www.econ.yale.edu/~shiller/data.htm), as packaged by
// github.com/datasets/s-and-p-500, which licenses its packaging under the ODC
// Public Domain Dedication and License (ODC-PDDL-1.0). Shiller's own page
// states no license terms: check before any paid use (docs/features.md,
// Planning).
//
// Input: ${source.url}
// Input SHA-256: ${source.sha256}
// Rows used: ${rows[0].month} to ${rows[rows.length - 1].month} (${rows.length} months), SHA-256 of those lines with the header: ${sha256(usedLines.join('\n'))}
`;
  return [
    header,
    `/** The month the first value starts in (YYYY-MM). */`,
    `export const HISTORY_FIRST_MONTH = '${first}';`,
    '',
    `/** How many months each series has. */`,
    `export const HISTORY_MONTHS = ${months.length};`,
    '',
    `/** Values are whole multiples of 1 / HISTORY_SCALE. */`,
    `export const HISTORY_SCALE = ${SCALE};`,
    '',
    series('STOCKS_REAL', 'Real total return of US stocks (the S&P composite with dividends), per month.', months, (m) => m.stocksReal),
    '',
    series('BONDS_REAL', 'Real total return of 10-year US government bonds held at constant maturity, per month.', months, (m) => m.bondsReal),
    '',
    series('INFLATION', 'US consumer price inflation, per month.', months, (m) => m.inflation),
    '',
  ].join('\n');
}

if (import.meta.main) {
  const argv = process.argv.slice(2);
  let input: string | undefined;
  let out = join(import.meta.dir, '..', 'lib', 'fire', 'history-data.ts');
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--out') out = argv[++i];
    else if (!input && !argv[i].startsWith('--')) input = argv[i];
    else {
      console.error(`Unknown argument ${JSON.stringify(argv[i])}.`);
      process.exit(1);
    }
  }
  if (!input) {
    console.error('Usage: bun run fire-data <path to the packaged CSV> [--out <path>]');
    process.exit(1);
  }
  const csv = readFileSync(input, 'utf8');
  const hash = sha256(csv);
  if (hash !== PINNED_SOURCE.sha256) {
    console.warn(`Note: this file's SHA-256 is ${hash}, not the pinned ${PINNED_SOURCE.sha256}. Writing it with its own hash.`);
  }
  writeFileSync(out, buildModule(csv, { url: hash === PINNED_SOURCE.sha256 ? PINNED_SOURCE.url : input, sha256: hash }));
  console.log(`Wrote ${out}.`);
}
